trigger:
    - main
    - dev

pool:
    vmImage: "windows-latest"

variables:
    buildConfiguration: "Release"
    appName: "InternetBulletin"
    artifactStagingDirectory: "$(Build.SourcesDirectory)/artifacts"
    webFolderName: "InternetBulletin.Web"

stages:
    - stage: DotNetBuild
      jobs:
          - job: API_Build
            steps:
                - task: UseDotNet@2
                  displayName: "Dotnet SDK"
                  inputs:
                      packageType: "sdk"
                      version: "9.0.x"
                      installationPath: $(Agent.ToolsDirectory)/dotnet

                - task: DotNetCoreCLI@2
                  displayName: "Dotnet Restore"
                  inputs:
                      command: "restore"
                      projects: "**/*.csproj"

                - task: DotNetCoreCLI@2
                  displayName: "Dotnet Build"
                  inputs:
                      command: "build"
                      projects: "**/*.csproj"
                      arguments: "--configuration $(buildConfiguration)"

                - task: DotNetCoreCLI@2
                  displayName: "Dotnet Publish"
                  inputs:
                      command: "publish"
                      projects: "**/*.csproj"
                      arguments: "--configuration $(buildConfiguration) --output $(artifactStagingDirectory)"

                - task: PublishBuildArtifacts@1
                  displayName: "Publish Artifacts"
                  inputs:
                      PathToPublish: "$(artifactStagingDirectory)"
                      ArtifactName: "drop"
                      publishLocation: "Container"

    - stage: NpmBuild
      jobs:
          - job: WEB_Build_Deploy
            pool:
                vmImage: "ubuntu-latest"
            steps:
                - task: AzureStaticWebApp@0
                  inputs:
                      app_location: "$(webFolderName)"
                      app_build_command: "npm run build"
                      output_location: "/dist"
                      azure_static_web_apps_api_token: "$(deployment_token)"
                  env:
                      NPM_CONFIG_FORCE: true
                      NPM_CONFIG_LEGACY_PEER_DEPS: true
